services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: librarydb
      MYSQL_USER: libraryuser
      MYSQL_PASSWORD: librarypass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init.sql:/docker-entrypoint-initdb.d/01-init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-prootpassword"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "5001:4000"
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/librarydb
      SPRING_DATASOURCE_USERNAME: libraryuser
      SPRING_DATASOURCE_PASSWORD: librarypass
    volumes:
      - backend_data:/app/data
      - ./uploads:/app/uploads
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend/frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=http://localhost:5001
    ports:
      - "3002:80"
    restart: unless-stopped
    environment:
      REACT_APP_API_URL: http://localhost:5001
    volumes:
      - frontend_data:/usr/share/nginx/html/data
    depends_on:
      - backend

volumes:
  db_data:
  backend_data:
  frontend_data: